### ISSUE TITLE
Add basic lesson information to README and so on

### ISSUE THREAD

**Issue by ewallace** [carpentries-incubator/good-enough-practices#1]
We need to add the basic information, as recommended in the lesson template README:

* [x] Decide on a title for your new lesson!
  Once you've chosen a new title, you can set the value for `lesson_title`
  in [`_config.yml`](_config.yml)
* [x] Add the URL to your built lesson pages to the repository description\*
* [x] Fill in the fields marked `FIXME` in:
  * the repository README
  * [`_config.yml`](_config.yml)
* [x] If you're going to be developing lesson material for the first time
  according to our design principles,
  consider reading the [Carpentries Curriculum Development Handbook][cdh]
* [ ] Consult the [Lesson Example][lesson-example] website to find out more about
  working with the lesson template
* ~~[ ] If you are planning to write your lesson in RMarkdown,
  [create a `main` branch and set this as the default branch in your repository settings][change-default-branch]~~
* [x] Update the repository README with relevant information about your lesson
  and delete this section

I am creating the new branch `basic-info-1` for these.

**Comment by ewallace** [comment]
@tzielins @aromanowski will we use Rmarkdown at all for this lesson? I don't think we would?

**Comment by tzielins** [comment]
Hi Edward, I will set up the template before Monday. I am kind of in the lessons mood.
I dont use Rmarkdown so I would prefered normal one. So it looks Rmarkdown is downvoted twice so can move on.

**Comment by ewallace** [comment]
I've made most of the changes and would like to request a review of those so we can merge in to the `gh-pages` branch.

Do we (any of us) need to create a Carpentries slack account?

**Comment by tzielins** [comment]
I hope I won't need slack :) I have never managed to use it productively. But I am more an async collaborator than on-line one.

**Comment by aromanowski** [comment]
Agree here on both! No need for Rmarkdown, I am ok with HTML + MD. I would
only open a slack channel if it is a requirement but otherwise I prefer to
discuss through github issues / email / meetings.

All the best,
A
