### ISSUE TITLE
Add official link and citation for phdcomics

### ISSUE THREAD

**Issue by ewallace** [carpentries-incubator/good-enough-practices#11]
[Figure 1. Four Stages of Data Loss](http://phdcomics.com/comics/archive.php/images/archive.php?comicid=382)

needs a citation and credit to PhDcomics.

**Comment by emma-wilson** [comment]
Not sure if this issue was still open but I added a link to the specific comic (https://phdcomics.com/comics/archive.php?comicid=1531) if that's helpful.

**Comment by ewallace** [comment]
Fixed a while ago.
