### ISSUE TITLE
Add Carpentries workshops to final episode

### ISSUE THREAD

**Issue by ewallace** [carpentries-incubator/good-enough-practices#115]
> But it would be great if you could list appropriate Carpentries workshops in this section. Not all topics have one, but som defintely do. Something along the lines of 'further learning'.

From @lexnederbragt review https://github.com/carpentries-lab/reviews/issues/24#issuecomment-1523302893

So add Carpentries workshop to final episode "What To Do Next".

**Comment by emma-wilson** [comment]
Thanks for the list of lessons @tobyhodges.

@ewallace, I've created a pull request (#117) to add the links @tobyhodges suggested.
