### ISSUE TITLE
Add to carpentries help-wanted page

### ISSUE THREAD

**Issue by ewallace** [carpentries-incubator/good-enough-practices#2]
Requesting @tobyhodges to list this repository on [the Help Wanted page](https://carpentries.org/help-wanted-issues/) so that any issues we label `help-wanted` will show up there for the wider community.

[Following up from proposals #64](https://github.com/carpentries-incubator/proposals/issues/64#issuecomment-792634546).

**Comment by tobyhodges** [comment]
Done ✅ You should see the lesson show up there if and when you label any issues on this repo with `good-first-issue` or `help-wanted`.

A request from my side: could you expand the set of Topics you have added to the description of this repository please? You can find some more guidance in [the appendix to the Curriculum Development Handbook](https://cdh.carpentries.org/the-carpentries-incubator.html#topic-tags). A complete set of topics will ensure this lesson appears correctly on [the Community Developed Lesson page](https://carpentries.org/community-lessons/). Feel free to ping me again if I can help.

**Comment by tobyhodges** [comment]
Done ✅ You should see the lesson show up there if and when you label any issues on this repo with `good-first-issue` or `help-wanted`.

A request from my side: could you expand the set of Topics you have added to the description of this repository please? You can find some more guidance in [the appendix to the Curriculum Development Handbook](https://cdh.carpentries.org/the-carpentries-incubator.html#topic-tags). A complete set of topics will ensure this lesson appears correctly on [the Community Developed Lesson page](https://carpentries.org/community-lessons/). Feel free to ping me again if I can help.
