### ISSUE TITLE
Combine resources with conclusions episode?

### ISSUE THREAD

**Issue by ewallace** [carpentries-incubator/good-enough-practices#26]
I am wondering if it makes sense to have `09-resources` as a separate episode, or instead to just include a list of other resources in the `08-conclusions` episode.

Also, we could be less generous in linking to the resources, is it too much?

**Comment by tzielins** [comment]
I was not thinking of "teaching" the resources, that is why I placed it after "conclusions." 

@ewallace  had compiled an extensive list of useful links which should not get lost. 

But going over long lists of links in a workshop is boooooring. Students could be told instead of the extra episode with handy meterials.  

I opt for rendering as an episode at it looks nicer and is more prominent than a document in extras.

**Comment by ewallace** [comment]
I'm convinced to have the links on a separate page. However, the problem with having it as an "episode" is that we won't actually be teaching it as an episode with time blocked off. So could we try it in `_extras`, then we can move it later if that doesn't work well?

**Comment by ewallace** [comment]
@tzielins, @aromanowski and I discussed this 19th July, we agree that conclusions and resources can be combined into a single episode. Let's address this at the hackathon #32.

**Comment by ewallace** [comment]
Further discussion with @FlicAnderson and @DimmestP, we agree that:
- `09-resources` should go into `_extras`, it is not a lesson episode
- "what we left out" section should also be taken out of `09-conclusion` and in to `_extras/resources`

**Comment by FlicAnderson** [comment]
Could potentially frame part of the conclusions section in terms of advice to different levels of users (for example students and early-stage researchers; post-docs and lab/support staff or mid-stage researchers; experienced; PIs).  

This could include recommendations to support colleagues to adopt some of these measures as this will help improve the overall level of the research group, as well as making colleagues better collaborators, and thus improving life for the learner themselves as a result! :)
