### ISSUE TITLE
Add funding information

### ISSUE THREAD

**Issue by ewallace** [carpentries-incubator/good-enough-practices#27]
Add funding information to README, as already in [fair-bio-practice](https://github.com/carpentries-incubator/fair-bio-practice).

> We are developing this lesson as part of the ED-DaSH consortium, supported by the "Data driven life science skills development - equipping society for the future" UKRI-MRC grant MR/V039075/1.

**Comment by ewallace** [comment]
@tobyhodges is there a help page or guidelines on how to include funding information on Carpentries lessons or carpentries-incubator? That would be useful for projects, like ours, where national funding agencies are contributing to community lesson development.

**Comment by tobyhodges** [comment]
Not at the moment. We are discussing something like a "Credit" page for lessons, as part of the new template. This would include a list of authors, maintainers, supporting organisations (including funding bodies), names of events where the lesson was first conceived, tested, etc.

While we wait for such a dedicated page, I recommend adding this kind of information to the About page in `_extras/`, above the two `{% include ... %} lines, to have it included in the built lesson site.
