### ISSUE TITLE
Expand Topics in description

### ISSUE THREAD

**Issue by ewallace** [carpentries-incubator/good-enough-practices#3]
Could you expand the set of Topics you have added to the description of this repository please? You can find some more guidance in [the appendix to the Curriculum Development Handbook](https://cdh.carpentries.org/the-carpentries-incubator.html#topic-tags). A complete set of topics will ensure this lesson appears correctly on [the Community Developed Lesson page](https://carpentries.org/community-lessons/). Feel free to ping me again if I can help.

_Originally posted by @tobyhodges in https://github.com/carpentries-incubator/good-enough-practices/issues/2#issuecomment-806759874_

**Comment by ewallace** [comment]
@tobyhodges after a long while I have addressed these. Any comments - anything missing?

**Comment by tobyhodges** [comment]
Looks good to me, @ewallace 👍
