### ISSUE TITLE
Hackathon 20th July to bring lesson up to alpha status

### ISSUE THREAD

**Issue by ewallace** [carpentries-incubator/good-enough-practices#32]
I think this lesson material could be brought up to alpha status by a small team of people working over a day or two. Let's schedule that?

**Comment by ewallace** [comment]
We are scheduling a hackathon Tuesday 20th July on this Good Enough Practices lesson

The primary goal of the hackathon is to bring lesson material up to "alpha" status, i.e. all material complete enough on carpentries incubator to deliver it to students. That includes for example drafting objectives and key points  #15, adding timings #33, and cleaning up placeholders in lesson pages #14. We can also address other issues of interest to hackathon participants, please tag with the #hackathon-july2021 label.

The hackathon will take place UK time 09:30 to 17:00, via zoom. Anyone who wants to be involved can join for as much or as little as they like. The draft plan is:
* 09:30 - kickoff meeting, discuss priorities and assign tasks to groups
* 10:15 - groups work on agreed tasks in breakout rooms
* 12:30 - lunch break
* 13:30 - check-in meeting, resolve pull requests if necessary, re-evaluate goals and groups
* 14:00 - groups work on agreed tasks in breakout rooms
* 16:00 - wrap-up meeting, agree top priority issues for lesson moving forward from hackathon

Please express interest by responding to this issue. If you include your email address then I can tag you into the calendar invite with zoom information.

Thanks!

**Comment by MatthiasMimault** [comment]
Hi, I'm willing to help ! You can add my mail matthias.mimault ~at~ hutton.ac.uk

**Comment by emma-wilson** [comment]
Hi Edward, I'm willing to help too. My email is emma.wilson at ed.ac.uk

**Comment by ppxasjsm** [comment]
@ewallace  Can you send me the zoom link please?

**Comment by ewallace** [comment]
@ppxasjsm, @emma-wilson , @MatthiasMimault - you should have a zoom link on a calendar invite in your email, let me know if you don't.

**Comment by ewallace** [comment]
I'm looking forward to this hackathon this coming Tuesday 20th! See some of you on zoom at 9:30am!

**Comment by ewallace** [comment]
Opening discussion agreed on priorities:
* key objectives for lessons #15 
* timings for lessons #33
* exercises #37

**Comment by FlicAnderson** [comment]
There will be a follow-up hackathon session on 11th August, 0930-1200 to follow up on the progress made during today's session.

**Comment by ewallace** [comment]
Thank you so much everyone! Really lovely and productive day. I enjoyed it and the lesson is in vastly better shape.
