### ISSUE TITLE
Use discussions as feedback on where the learners are at

### ISSUE THREAD

**Issue by ewallace** [carpentries-incubator/good-enough-practices#35]
@aromanowski pointed out that the discussions are the instructor's best opportunity to figure out where the learners are at and how to adjust the material accordingly.

Needs to be updated in [instructor notes](https://github.com/carpentries-incubator/good-enough-practices/blob/gh-pages/_extras/guide.md)

**Comment by ewallace** [comment]
Addressed in [44318af](https://github.com/carpentries-incubator/good-enough-practices/pull/109/commits/44318af454273491194fbad16773ef57cf6f65c8), so will be fixed by #109

**Comment by ameynert** [comment]
Can close as addressed above.
