### ISSUE TITLE
Linking data management episode to content on file naming and identifiers

### ISSUE THREAD

**Issue by aromanowski** [carpentries-incubator/good-enough-practices#42]
During the hackathon, together with @egountouna and @ggrimes we discussed about the possibility of linking to further content on file naming and identifiers. A good place to do this would be at some place under the "Create the data you wish to see in the world" heading.

**Comment by ewallace** [comment]
Does this still need addressing?

**Comment by ameynert** [comment]
Addressed in a commit to #109
