### ISSUE TITLE
proposed exercise for data management episode on good documenting

### ISSUE THREAD

**Issue by aromanowski** [carpentries-incubator/good-enough-practices#43]
During the hackathon, together with @egountouna and @ggrimes it was discussed that we should consider adding  a proper exercise with different examples of good documentation and generate a discussion around that. Although the timing is already pretty tight.

**Comment by ewallace** [comment]
I think here that:

- timing is tight
- documentation review is addressed later in the README exercise in [04-collaboration.md](https://github.com/carpentries-incubator/good-enough-practices/blob/gh-pages/_episodes/04-collaboration.md)

So I'm closing this issue. If anyone still wants to propose an improvement here that's fine.
