### ISSUE TITLE
Heading that names 'multiple tables' in data management episodes leads to confusion

### ISSUE THREAD

**Issue by aromanowski** [carpentries-incubator/good-enough-practices#44]
During the hackathon, together with @egountouna and @ggrimes we found the heading "Anticipate the need to use multiple tables, and use a unique identifier for every record" a little bit confusing. We should consider rephrasing this bit. The paragraph talks about using unique ids to link multiple tables (in a database kind of style).

**Comment by ewallace** [comment]
I think the text works, but it could be clarified and simplified. Leaving here with a "help wanted" label for now, hoping that someone will have a brainwave as to how to clarify the section.

**Comment by ameynert** [comment]
Updated to:

- Record different data types in individual tables as appropriate (e.g. sample metadata may be kept separately from sequencing experiment metadata)
- Use unique identifiers for every record in a table, allowing linkages between tables (e.g. sample identifiers are recorded in the sequencing experiment metadata)

In #109
