### ISSUE TITLE
Include callout or section about GDPR, data protection, anonymisation in data sharing section of data management episode

### ISSUE THREAD

**Issue by emma-wilson** [carpentries-incubator/good-enough-practices#48]

**Comment by FlicAnderson** [comment]
I think there's possibly some overlap here with the section we've added 'Working with sensitive data' in episode `04-collaboration.md` - so it's worth keeping an eye to avoid repetition and to ensure the collab section doesn't repeat content from the data management section.

**Comment by emma-wilson** [comment]
Hi @ameynert, I think this has been addressed sufficiently
