### ISSUE TITLE
Add activity about good and bad file names to data management episode

### ISSUE THREAD

**Issue by emma-wilson** [carpentries-incubator/good-enough-practices#49]
Use slide 3 as example http://www2.stat.duke.edu/~rcs46/lectures_2015/01-markdown-git/slides/naming-slides/naming-slides.pdf

**Comment by ewallace** [comment]
Addressed by the "Naming and sorting" exercise in [05-project_organization.md](https://github.com/carpentries-incubator/good-enough-practices/blob/gh-pages/_episodes/05-project_organization.md). Closing.
