### ISSUE TITLE
Create learner profiles focused on half-day workshop

### ISSUE THREAD

**Issue by ewallace** [carpentries-incubator/good-enough-practices#5]
Create learner profiles focused on a half-day "good enough practices in research computing" workshop. These are complementary to the learner profiles that @tzielins and @aromanowski have created for the longer "FAIR science in practice" workshop.

@ppxasjsm and @JenDaub have agreed to contribute to learner profiles.

I started a new branch `learner-profiles-5`, and added a profile to `_extras/learner-profiles.md`

**Comment by ewallace** [comment]
From discussion 29 March 2021: we definitely need a postdoc learner profile.

I will write "Stuart Simulator" for this.

**Comment by ewallace** [comment]
Created "Stuart Simulator" in [_extras/learner-profiles.md](https://github.com/carpentries-incubator/good-enough-practices/blob/learner-profiles-5/_extras/learner-profiles.md). 
He might seem oddly familiar to people I worked with ten years ago.

**Comment by ppxasjsm** [comment]
I feel like I missed an essential discussion on the 29th March somehow.

**Comment by ewallace** [comment]
That was a meeting with @tzielins, @aromanowski and I, who are the core team on this lesson from the Ed-DaSH grant. @ppxasjsm - should we invite you to the next one?

**Comment by ppxasjsm** [comment]
If you think it would be useful for me contributing then yes. Or maybe we can have a very quick discussion at some point what you are after with regard to the learner profiles. (5-10 mins)

**Comment by ppxasjsm** [comment]
How many profiles are you after?

**Comment by ewallace** [comment]
I think 4 is a good number. So hoping for one each from Toni and Jen?

**Comment by ppxasjsm** [comment]
I added 3 more profiles. Let me know what you think, or if you can think of others. Obviously feel free to expand as well. This is just a basic sketch at the moment.

**Comment by ewallace** [comment]
@ppxasjsm these look great!

@JenDaub - we have five profiles, which is already a good number. Might it be more efficient for you to edit/upgrade/clarify the ones we already drafted, rather than adding new ones?

**Comment by tzielins** [comment]
I enjoy seeing as every profile describes learners from scientific computing angle, ie with some coding experience.

**Comment by JenDaub** [comment]
Hi all, sorry I dropped the ball on this one. New job and then had my vaccination on Wed which knocked me over on Thu. Does not sound like you need any more profiles. Will go check out those that are there. My main concern is that you make sure all the profiles are not just young PhD students.

**Comment by ppxasjsm** [comment]
I think this has been achieved and will close issue.
