### ISSUE TITLE
Software episode upgrades

### ISSUE THREAD

**Issue by ewallace** [carpentries-incubator/good-enough-practices#50]
- tidy up language
- fix links
- add reference to modular code for "much has been written about..."

**Comment by ewallace** [comment]
We could add one of @mikej888 or @npch's blogposts on [what makes good code good](https://www.software.ac.uk/blog/2016-10-07-what-makes-good-code-good-digital-social-research-view) to here or to our resources section?

**Comment by FlicAnderson** [comment]
Could also make upgrades to the 'questions' section, as some of these (e.g. the debugging question) don't necessarily cover the lesson content explicitly?  It could be reworded for a better fit I think.
