### ISSUE TITLE
Overview required for Keeping Track of Changes lesson

### ISSUE THREAD

**Issue by FlicAnderson** [carpentries-incubator/good-enough-practices#58]
Keeping Track of Changes lesson needs a completed Overview section (timings, questions, objectives). 

Currently this hasn't been added, and should match the lesson content.

**Comment by MatthiasMimault** [comment]
Formatting decision required between "Manual versioning" and "Version control system" (the first one is a list of actions (2 items) whilst the second one is a list of one item with boxes)

2 boxes at the end could be normal paragraphs ("How version control works" and "git resources")
