### ISSUE TITLE
Formatting fixes required for Keeping Track of Changes

### ISSUE THREAD

**Issue by FlicAnderson** [carpentries-incubator/good-enough-practices#59]
Formatting fixes needed for Keeping Track of Changes lesson: 
* fix (or remove) broken reference/link formats (e.g. 'Dropbox[^20]'), link references to be found at: https://swcarpentry.github.io/good-enough-practices-in-scientific-computing/ 
* remove references to points from the good enough practices e.g.'(5f)' 
* remove example boxes.

**Comment by FlicAnderson** [comment]
Also check formats are correct for exercise boxes (for example first exercise: https://github.com/carpentries-incubator/good-enough-practices/commit/1eb3d4d473c3f9f97afec058c31f6fef3de98961 is about "which of these issues can you relate to?", so it could be perhaps a multichoice or true/false, and learners could report back 'how many' they identify with?)

**Comment by ewallace** [comment]
I think this is fixed by #63. Closing.
