### ISSUE TITLE
Mention Data Management Plans in Data episode

### ISSUE THREAD

**Issue by ewallace** [carpentries-incubator/good-enough-practices#88]
UK funders require a data management plan.

Learners could be encouraged to ask their group about the group/grant data management plan.

What's the best way to add that to the data episode?

**Comment by emma-wilson** [comment]
Currently working on this -- will create pull request when finished (either today or tomorrow).

**Comment by emma-wilson** [comment]
Created the pull request now -- feel free to change anything I've added if it's not useful
