### ISSUE TITLE
Lesson authorship for peer review

### ISSUE THREAD

**Issue by ewallace** [carpentries-incubator/good-enough-practices#93]
Hello!

We are gearing up for submission of this Good Enough Practices lesson to Carpentries Lab for peer review and publication. So it's time to check that we have the authorship represented fairly.
Current authors listed are 
- @tzielins
- @aromanowski
- @ameynert added in [9d3f0a0](https://github.com/carpentries-incubator/good-enough-practices/pull/92/commits/9d3f0a0d0ad36a1257d57d809aaed4b542955852)

[Other contributors](https://github.com/carpentries-incubator/good-enough-practices/graphs/contributors) include:
- @MatthiasMimault
- @DimmestP 
- @FlicAnderson 
- @emma-wilson 
- @JenDaub
- @ppxasjsm
- @jjyh
- @zkamvar
- @ggrimes
- @tobyhodges 
- @egountouna didn't you contribute as well?

Please, if you would like to be listed as an author, edit the AUTHORS file and make a pull request.
If you would not, please comment on this thread.

Thanks,
Edward

**Comment by zkamvar** [comment]
Thank you for checking for authorship and for providing a way out! My only contribution to this repository was https://github.com/carpentries-incubator/good-enough-practices/pull/85, which was maintenance for infrastructure unrelated to the lesson content. I do not believe I should be listed in the AUTHORS file.

**Comment by JenDaub** [comment]
Hi Edward, Thanks for checking, I do not believe I should be listed in the AUTHORS file either.

**Comment by egountouna** [comment]
Hi, thank you for checking, it's been a while and I'm not sure what the criteria are exactly. As far as I recall, I participated in a workshop/hackathon to shape the content and contributed an exercise to the data management section.

**Comment by tobyhodges** [comment]
Thanks @ewallace I would not like to be listed as an author. My contributions have all been very minor, and mostly cosmetic. Furthermore, I would not like to introduce any potential conflict of interest as I act as Editor to the lesson review process in The Carpentries Lab.

**Comment by ewallace** [comment]
Thanks everyone.

- @emma-wilson is making some further contributions and authorship will be clear.

I am still waiting to hear from:
- @tzielins
- @aromanowski
- @MatthiasMimault
- @DimmestP
- @FlicAnderson
- @ppxasjsm
- @ggrimes

Please do let me know in this thread.

**Comment by tzielins** [comment]
For authorship I populated the main content and I was at hackatone.

**Comment by FlicAnderson** [comment]
Hi, apologies for late response. I attended a hackthon and added an exercise, so I've created a PR adding my name to AUTHORS file: https://github.com/carpentries-incubator/good-enough-practices/pull/97
