### ISSUE TITLE
Prepare paper.md and paper.bib for JOSE submission

### ISSUE THREAD

**Issue by ewallace** [carpentries-incubator/good-enough-practices#95]
This lesson has been submitted to Carpentries lab for peer review: https://github.com/carpentries-lab/reviews/issues/24

To complete the review and be accepted for publication in JOSE, it will need paper.md and paper.bib files.
The requirements are described in
[instructions on learning module submission at JOSE](https://openjournals.readthedocs.io/en/jose/submitting.html#how-to-prepare-a-learning-module-submission)

We'll need to agree the author list first, see #93

**Comment by ewallace** [comment]
I now have a draft paper. It may be too long.

Requesting review on the pull request from @ameynert.

It would be great to double-check that everyone's name (including middle initials), affiliation and email is correct in [paper.md](https://github.com/carpentries-incubator/good-enough-practices/blob/jose-paper-95/paper.md). Any other comments and feedback on the paper are welcome. I'm tagging @tzielins @aromanowski @emma-wilson @FlicAnderson @MatthiasMimault as well to check the details are correct.

**Comment by ewallace** [comment]
Note: quick check that the paper compiles correctly at https://whedon.theoj.org

**Comment by MatthiasMimault** [comment]
> I now have a draft paper. It may be too long.
> 
> Requesting review on the pull request from @ameynert.
> 
> It would be great to double-check that everyone's name (including middle initials), affiliation and email is correct in [paper.md](https://github.com/carpentries-incubator/good-enough-practices/blob/jose-paper-95/paper.md). Any other comments and feedback on the paper are welcome. I'm tagging @tzielins @aromanowski @emma-wilson @FlicAnderson @MatthiasMimault as well to check the details are correct.

Good for me ! Great job

**Comment by ewallace** [comment]
Thanks everyone, @ameynert has now reviewed and improved the paper. I will give until Tuesday 2023-06-13 for comments and so on before merging and adding it to the peer-review process at Carpentries Lab.

**Comment by tzielins** [comment]
It looks good and crisps. I fixed my name on the paper branch - not sure how it affects the pull request. 
Good look with the submission, we were told that our course was out of scope so I am curious how this one goes.

**Comment by aromanowski** [comment]
> I now have a draft paper. It may be too long.
> 
> Requesting review on the pull request from @ameynert.
> 
> It would be great to double-check that everyone's name (including middle initials), affiliation and email is correct in [paper.md](https://github.com/carpentries-incubator/good-enough-practices/blob/jose-paper-95/paper.md). Any other comments and feedback on the paper are welcome. I'm tagging @tzielins @aromanowski @emma-wilson @FlicAnderson @MatthiasMimault as well to check the details are correct.

Hi @ewallace!
I cannot see the paper.md file but in addition to the one that Tomek would have from BioRDM, could you also please add my current one? It is as follows:
- Plant-Environment Signaling Group, Dept. of Biology, Faculty of Science, Utrecht University, Utrecht, 3584 CH, The Netherlands.

All the best,
Andres
